const bikes = [
 {id:'lbx',brand:'Sur-Ron',name:'Light Bee X',cat:['emoto','trail'],tone:'#d9e6d2',speed:'47 mph',power:'8 kW',battery:'60V 40Ah',range:'47 mi',weight:'126 lb',seat:'32.7 in',wheels:'19 / 18 in',price:'≈ $4,000',desc:'The lightweight benchmark: compact aluminum chassis, huge aftermarket and a playful trail-first feel.',best:'Riders who value agility, parts support and a proven platform.',legal:'Off-road model is not street legal. L1e road versions exist in some non-US markets.',source:[['Sur-Ron NZ specs','https://sur-ron.co.nz/pages/light-bee-x-my25'],['2025 specification summary','https://surron.ae/blogs/info/what-are-the-2025-surron-light-bee-x-specs']]},
 {id:'ultra',brand:'Sur-Ron',name:'Ultra Bee',cat:['emoto','trail'],tone:'#e5decf',speed:'56 mph',power:'12.5 kW',battery:'74V 55Ah',range:'87 mi*',weight:'187 lb',seat:'35.8 in',wheels:'19 / 19 in',price:'≈ $6,500',desc:'A larger, motorcycle-like step up with traction control, adjustable regen and substantial suspension.',best:'Experienced riders wanting more chassis, range and stability than Light Bee-class machines.',legal:'US off-road versions are not street legal; homologated road variants differ by market.',source:[['Sur-Ron global','https://www.sur-ron.com/'],['Sur-Ron encyclopedia','https://en.wikipedia.org/wiki/Sur-Ron']]},
 {id:'rtrlite',brand:'Electro & Co.',name:'ETM RTR Lite',cat:['pitbike'],tone:'#d9dedd',speed:'45+ mph',power:'5 kW',battery:'60V 20Ah',range:'20–40 mi',weight:'120 lb',seat:'30 in',wheels:'14 / 12 in',price:'≈ $2,199',desc:'Compact entry ETM with a tool-free hot-swap battery and the same modular tubular platform as its faster siblings.',best:'Pit-bike riders wanting compact geometry and an upgradeable starting point.',legal:'Closed-course/off-road use only.',source:[['Official user guide','https://support.electroandcompany.com/hc/en-us/articles/45057311013779-ETM-RTR-Lite-User-Guide'],['GoPowerSports specs','https://www.gopowersports.com/electro-co-etm-rtr-lite-electric-pit-bike/']]},
 {id:'rtrsport',brand:'Electro & Co.',name:'ETM RTR Sport',cat:['pitbike'],tone:'#e8d8ce',speed:'55+ mph',power:'8 kW',battery:'72V 25Ah',range:'30–50 mi',weight:'130 lb',seat:'30 in',wheels:'14 / 12 in',price:'≈ $2,999',desc:'The sweet-spot ETM: 72 volts, stronger Revolver IPM motor and adjustable suspension in true pit-bike dimensions.',best:'Teens and adults seeking serious speed in a small-wheel package.',legal:'Closed-course/off-road use only.',source:[['Detailed current specs','https://throttletheorypowersports.com/products/etm-rtr-sport-1'],['Official support','https://support.electroandcompany.com/']]},
 {id:'rtrxl',brand:'Electro & Co.',name:'ETM RTR XL',cat:['pitbike','trail'],tone:'#d5e1e0',speed:'65+ mph',power:'16 kW',battery:'72V 35Ah',range:'30–60 mi',weight:'145 lb',seat:'32 in',wheels:'17 / 14 in',price:'≈ $3,799',desc:'A stretched big-wheel ETM with Alpha-derived power, full 420 chain and more room for taller riders.',best:'Riders who like pit-bike character but need more room and stability.',legal:'Closed-course/off-road use only.',source:[['EMOTO detailed specs','https://rideemoto.com/products/etm%E2%84%A2-rtr-xl'],['Official Electro & Co.','https://electroandcompany.com/']]},
 {id:'alpha',brand:'Electro & Co.',name:'ETM RTR Alpha',cat:['pitbike'],tone:'#ead5d0',speed:'70+ mph',power:'18 kW',battery:'72V 35Ah / 92V full',range:'30–60 mi',weight:'≈ 140 lb',seat:'30 in',wheels:'14 / 12 in',price:'≈ $3,999',desc:'The high-output ETM flagship, pairing compact pit geometry with an extreme full-charge voltage and race-oriented output.',best:'Expert riders who specifically want maximum power in the compact ETM chassis.',legal:'Closed-course/off-road use only. Not a beginner machine.',source:[['Current dealer listing','https://ronsterrides.com/products/etm-rtr-alpha'],['Official support data','https://support.electroandcompany.com/hc/en-us/articles/48600704392467-Programming-the-RTR-Rizzler-Display']]},
 {id:'ss2',brand:'E Ride Pro',name:'Pro SS 2.0',cat:['emoto','trail'],tone:'#e3e4da',speed:'60 mph',power:'12 kW',battery:'72V 40Ah',range:'50+ mi',weight:'139 lb',seat:'32.7 in',wheels:'19 / 19 or 18',price:'$4,599',desc:'A fast 72-volt Light Bee-class e-moto with a swappable Samsung pack and adjustable sport suspension.',best:'Buyers prioritizing speed and battery capacity without moving to Ultra Bee size.',legal:'Sold for off-road use; verify local road-version certification separately.',source:[['Official product page','https://www.eridepro.com/products/pro-ss-2-0'],['Official manuals','https://www.eridepro.com/pages/user-manual']]},
 {id:'ss3',brand:'E Ride Pro',name:'Pro SS 3.0',cat:['emoto','trail'],tone:'#d5dfd8',speed:'60 mph',power:'15.8 kW',battery:'72V 50Ah',range:'62+ mi',weight:'167 lb',seat:'32.7 in',wheels:'19 / 18 in',price:'$4,699',desc:'Bigger 3.6 kWh capacity, stronger peak output and refined suspension make the 3.0 a substantial all-terrain upgrade.',best:'Trail riders who want long claimed range and strong out-of-box power.',legal:'US product is off-road. L1e/L3e homologated versions are sold in some countries.',source:[['Official product page','https://www.eridepro.com/products/pro-ss-3-0-off-road-fatty'],['Official manuals','https://www.eridepro.com/pages/user-manual']]},
 {id:'ss4',brand:'E Ride Pro',name:'Pro SS 4.0',cat:['emoto','trail'],tone:'#e5d8d4',speed:'≈ 60–62 mph',power:'18 kW',battery:'72V 50Ah',range:'64+ mi',weight:'167 lb',seat:'32.7 in',wheels:'19 / 18 in',price:'$4,999',desc:'The newest SS adds Race mode, smart swappable pouch-cell battery, Fastace suspension and four-piston brakes.',best:'Experienced trail riders shopping the most complete SS platform.',legal:'Off-road recreational equipment; not intended for public roads.',source:[['Luna Cycle full specs','https://lunacycle.com/eride-pro-4-0/'],['Current dealer overview','https://ampedbikes.com/products/e-ride-pro-ss-4-0']]},
 {id:'x3',brand:'Talaria',name:'X3 / XXX',cat:['emoto'],tone:'#dce1d3',speed:'≈ 50 mph',power:'6.5 kW',battery:'60V 40Ah',range:'≈ 50 mi',weight:'125 lb',seat:'31.7 in',wheels:'17 / 17 in',price:'≈ $3,250',desc:'Low, compact and urban-styled, the belt-primary X3 is Talaria’s most approachable full-power platform.',best:'Shorter riders and commuters with legal private/off-road places to ride.',legal:'US off-road trim is not an e-bike legally. L1e versions exist in some markets.',source:[['2025 Talaria brochure','https://static1.squarespace.com/static/60b878075c4e06485877b540/t/68a69fdb86663f63469af2b6/1755750363229/2025%2BTalaria%2BSales%2BBrochure%2BXXX%2BSpecs.pdf']]},
 {id:'mx3',brand:'Talaria',name:'Sting MX3',cat:['emoto','trail'],tone:'#e6ddce',speed:'47 mph',power:'6 kW',battery:'60V 38.4Ah',range:'62 mi*',weight:'≈ 145 lb',seat:'33.1 in',wheels:'19 / 17 in',price:'≈ $3,400',desc:'The original Sting formula: gearbox primary drive, adjustable regen and a stable forged-alloy chassis.',best:'Value-minded trail riders who prefer a gearbox over a belt primary.',legal:'Off-road trim is not street legal; road homologation depends on market.',source:[['Talaria MX3 specifications','https://talariausabikes.com/product/talaria-sting-mx3/'],['Talaria brochure','https://resources.tmp.dk/product-files/46-talaria-brochure-2024.pdf']]},
 {id:'mx4',brand:'Talaria',name:'Sting R MX4',cat:['emoto','trail'],tone:'#d2dedc',speed:'53 mph',power:'8 kW',battery:'60V 45Ah',range:'53 mi*',weight:'≈ 145 lb',seat:'33.1 in',wheels:'19 / 17 in',price:'≈ $4,200',desc:'The stronger Sting R pairs an 8 kW tune and larger battery with the durable Talaria gearbox platform.',best:'Riders wanting balanced power, proven trail geometry and broad parts support.',legal:'Typically sold in the US for off-road use only.',source:[['Talaria product family','https://talaria.cn/'],['Talaria technical brochure','https://resources.tmp.dk/product-files/46-talaria-brochure-2024.pdf']]},
 {id:'mx5',brand:'Talaria',name:'Sting Pro MX5',cat:['emoto','trail'],tone:'#e9d8ca',speed:'59 mph',power:'13.4 kW',battery:'72V 40Ah',range:'75 mi*',weight:'≈ 168 lb',seat:'33.1 in',wheels:'19 / 19 in',price:'≈ $4,700',desc:'Talaria’s 72-volt Sting Pro adds moto-style brakes, stronger drivetrain hardware and serious peak power.',best:'Aggressive trail riders choosing between SS 3.0-class machines.',legal:'US MX version is off-road only; confirm the exact battery revision and certification with dealer.',source:[['Talaria 2024 brochure','https://resources.tmp.dk/product-files/46-talaria-brochure-2024.pdf']]},
 {id:'bonnell',brand:'Bonnell',name:'775MX',cat:['trail','emoto'],tone:'#d5e3d3',speed:'38 mph',power:'25 kW peak',battery:'72V 35Ah',range:'≈ 40–75 mi',weight:'75 lb',seat:'Size-dependent',wheels:'27.5 / 27.5 in',price:'$5,495',desc:'A category-blurring 75-pound machine with downhill-bike geometry, pedals and extraordinary claimed peak output.',best:'Advanced MTB riders who want maximum power-to-weight and premium suspension.',legal:'High output means it generally does not qualify as a legal e-bike despite pedals.',source:[['Bonnell help center','https://ridebonnell.com/pages/help-center'],['Electric Cycle Rider specs','https://parts.electriccyclerider.com/products/bonnell-775-mx-the-fastest-electric-mountain-bike']]},
 {id:'dart24',brand:'Crew Bike Co.',name:'Dart 24',cat:['legal'],tone:'#e4ded4',speed:'28 mph off-road',power:'750 W',battery:'48V 14Ah',range:'Up to 40 mi',weight:'64 lb',seat:'Bench',wheels:'24 × 3 in',price:'$1,399',desc:'A full-size BMX-inspired pedal bike with hydraulic brakes, four modes and a long bench seat.',best:'Taller urban riders wanting pedals and relaxed ride-out style.',legal:'28 mph Offroad mode makes this an out-of-class electric vehicle in California; restrictions vary locally.',source:[['Official product page','https://crewbikeco.com/products/crew-dart-24']]},
 {id:'dart20',brand:'Crew Bike Co.',name:'Dart 20',cat:['legal'],tone:'#d4dfdf',speed:'20 mph',power:'750 W',battery:'48V 10Ah',range:'Up to 40 mi',weight:'61 lb',seat:'Bench',wheels:'20 × 4 in',price:'$1,299',desc:'A compact, factory-configured Class 2 pedal e-bike with fat tires, thumb throttle and hydraulic discs.',best:'Shorter riders seeking a street-oriented, approachable Class 2 ride.',legal:'Factory configuration meets California Class 2 limits; always verify state and local rules.',source:[['Official product page','https://crewbikeco.com/products/crew-dart-20']]},
 {id:'drift',brand:'Electro & Co.',name:'E-Drift Kart',cat:['pitbike'],tone:'#ead8ce',speed:'40 mph',power:'5 kW',battery:'60V 26Ah',range:'Up to 40 mi*',weight:'210 lb',seat:'Adjustable',wheels:'10 × 4.5–5',price:'Check maker',desc:'A rear-drive electric drift kart with high-angle steering, reverse and replaceable bumpers—not a bike, but too fun to leave out.',best:'Private-property drifting and closed-course recreation.',legal:'Closed-course/private-property machine; not for public roads.',source:[['Official specification page','https://electroandcompany.com/pages/e-drift-kart']]}
];

const bikeImages={lbx:'https://www.surroner.com/wp-content/uploads/2025/12/hf_20260627_185854_5f9eadf4-0bff-48f4-afad-49e4c7c51588.png',ultra:'https://sur-ronbikes.com/cdn/shop/files/sur-ron-ultra-bee-x-2025-off-road-carbon-black.webp?v=1772620699',rtrlite:'https://www.gopowersports.com/_astro/2b47c85e8f6366bf224d40762b7feea99a5f40d9.Bt0Hv5zl_18FVLT.webp',rtrsport:'https://throttletheorypowersports.com/cdn/shop/files/IMG_4102.jpg?v=1779932739',rtrxl:'https://rideemoto.com/cdn/shop/files/etm-rtr-xl-electro-co-emoto-supply-co-8688666_1200x1200.webp?v=1779178746',alpha:'https://ronsterrides.com/cdn/shop/files/rtralpha.png?v=1780886250',ss2:'https://www.eridepro.com/cdn/shop/files/10-23-02.jpg?v=1761201250',ss3:'https://www.eridepro.com/cdn/shop/files/3.0withnewshockfender.0withnewshockfender.0withnewshockfender.png?v=1785917911',ss4:'https://ampedbikes.com/cdn/shop/files/ERideProSS4.0FrontAngle_b71f65a2-3326-4089-869b-50513f52882e.jpg?v=1787599222&width=1024',x3:'https://talariausabikes.com/wp-content/uploads/2024/12/talaria-xxx-red-edition.jpg',mx3:'https://talariausabikes.com/wp-content/uploads/2024/12/TALARIA-STING-MX3.webp',mx4:'https://cdn11.bigcommerce.com/s-9vkjq73s/products/2264/images/14664/TALARIA_WHITEOUT_copy__98524.1680340334.500.750.png?c=2',mx5:'https://cdn11.bigcommerce.com/s-9vkjq73s/products/2677/images/16622/MX5_03_WHITEOUT__62588.1725101281.500.750.png?c=2',bonnell:'https://cdn.shopify.com/s/files/1/0861/5883/6028/files/775_MX_RightSideView_TexasGrey_01.webp?v=1780937752',dart24:'https://crewbikeco.com/cdn/shop/files/Dart24-MatteBlack-CS.png?v=1766595804',dart20:'https://crewbikeco.com/cdn/shop/files/Dart20-MatteSilver-CS_1.jpg?v=1770227123',drift:'https://electroandcompany.com/cdn/shop/files/Untitled_design_20.png?v=1707538835'};
bikeImages.lbx='assets/bikes/surron-lbx.png?v=2';
bikeImages.ultra='assets/bikes/surron-ultra-offroad.png?v=2';
bikeImages.drift='assets/bikes/electro-drift-kart.jpg?v=1';
const labels={all:'All rides',pitbike:'Pit bike',legal:'Legal / pedal e-bike',emoto:'E-moto',trail:'Trail bike'};
const actionVideos=[
 {id:'lbx',creator:'Starline World',title:'I Turned My Stock Surron Into a Fully Built Monster',video:'O9PRIjS9LzY'},
 {id:'ultra',creator:'Ultra Ryder',title:'UltraRyder Nearly Missed This Rideout',video:'XQywvCxmHmM'},
 {id:'rtrlite',creator:'Rawstuntz',title:'ETM RTR Lite Real Range Test — Exploring LA',video:'TYiskO9517g'},
 {id:'rtrsport',creator:'Talaria Boys',title:'World’s Best Pit Bike? RTR Sport Review',video:'rU8Xjg6xIKw'},
 {id:'rtrxl',creator:'Connor G',title:'ETM RTR XL First Ride — 16 kW, 65 MPH',video:'cxdgpgVJqEU'},
 {id:'alpha',creator:'Sur Ronster',title:'The World’s Fastest Mini Bike',video:'0x2KeYKKrD0'},
 {id:'ss2',creator:'Sur Ronster',title:'The New E-Ride Pro 2.0',video:'g9DkBElUPLY'},
 {id:'ss3',creator:'Rawstuntz',title:'Is the E Ride Pro 3.0 Worth It? First Ride',video:'-PC52niQ1sg'},
 {id:'ss4',creator:'Electrix Moto',title:'E Ride Pro 4.0 Review and Ride',video:'gwokb4oryOU'},
 {id:'x3',creator:'Sur Ronster',title:'Talaria XXX Official Test and Review',video:'jKU2HafC4pg'},
 {id:'mx3',creator:'KDLElectric',title:'Talaria MX3 2,000-Mile Review and Ride',video:'bznVp9Ybnw8'},
 {id:'mx4',creator:'Power Curve Cycles',title:'First Ride on the Talaria Sting R MX4',video:'Mmr01lnijB8'},
 {id:'mx5',creator:'Sur Ronster',title:'The New Talaria MX5 Is Almost Perfect',video:'1CBYZ1pbDt4'},
 {id:'bonnell',creator:'Sur Ronster',title:'The Most Powerful Electric Bike',video:'MC8LE7kRDMI'},
 {id:'dart24',creator:'Crew Bike Co.',title:'Crew Dart V3 Bike Check and Feature Breakdown',video:'laKzmMhYW44'},
 {id:'dart20',creator:'BIKE LIFE GEE',title:'Crew Dart E-Bike — Trails and Streets',video:'qUyAS3LdWw4'},
 {id:'drift',creator:'Electro & Company',title:'This E-Drift Kart Changes Everything',video:'60-57pQtuuw'}
];
let filter='all', selected=[], currentDetailIndex=0;
const specFilters={power:'all',speed:'all',range:'all',size:'all'};
const sizeGroups={lbx:'mid',ultra:'full',rtrlite:'compact',rtrsport:'compact',rtrxl:'mid',alpha:'compact',ss2:'mid',ss3:'mid',ss4:'mid',x3:'mid',mx3:'mid',mx4:'mid',mx5:'mid',bonnell:'full',dart24:'full',dart20:'compact',drift:'full'};
const grid=document.querySelector('#bikeGrid'), search=document.querySelector('#searchInput');

function numericValue(value){const values=(value.match(/[\d.]+/g)||[]).map(Number);return values.length?Math.max(...values):0}
function powerValue(value){const number=numericValue(value);return /\bkW\b/i.test(value)?number:number/1000}
function matchesSpecs(b){const power=powerValue(b.power),speed=numericValue(b.speed),range=numericValue(b.range);return (specFilters.power==='all'||specFilters.power==='under8'&&power<8||specFilters.power==='8to15'&&power>=8&&power<15||specFilters.power==='15plus'&&power>=15)&&(specFilters.speed==='all'||specFilters.speed==='under40'&&speed<40||specFilters.speed==='40to55'&&speed>=40&&speed<55||specFilters.speed==='55plus'&&speed>=55)&&(specFilters.range==='all'||specFilters.range==='under40'&&range<40||specFilters.range==='40to60'&&range>=40&&range<60||specFilters.range==='60plus'&&range>=60)&&(specFilters.size==='all'||sizeGroups[b.id]===specFilters.size)}

function render(){
 const q=search.value.toLowerCase().trim();
 const shown=bikes.filter(b=>(filter==='all'||b.cat.includes(filter))&&matchesSpecs(b)&&(`${b.brand} ${b.name} ${b.power} ${b.battery} ${b.desc}`.toLowerCase().includes(q)));
 grid.innerHTML=shown.map(b=>`<article class="bike-card" data-id="${b.id}" style="--tone:${b.tone}" tabindex="0">
   <div class="card-visual"><span class="category-tag">${labels[b.cat[0]]}</span><button class="compare-check ${selected.includes(b.id)?'selected':''}" aria-label="Add ${b.name} to compare" data-compare="${b.id}">${selected.includes(b.id)?'✓':'+'}</button><img class="bike-photo" src="${bikeImages[b.id]}" alt="${b.brand} ${b.name}" loading="lazy" onerror="this.classList.add('is-broken')"></div>
   <div class="card-body"><span class="brandline">${b.brand}</span><h3>${b.name}</h3><div class="mini-specs"><div><b>${b.speed}</b><span>Top speed</span></div><div><b>${b.power}</b><span>Peak power</span></div><div><b>${b.battery}</b><span>Battery</span></div></div><div class="card-link"><span>View full profile</span><span>↗</span></div></div></article>`).join('');
 document.querySelector('#resultCount').textContent=`Showing ${shown.length} machine${shown.length===1?'':'s'}`;
 document.querySelector('#emptyState').hidden=shown.length>0;
 document.querySelector('#resetSpecFilters').disabled=Object.values(specFilters).every(value=>value==='all');
 document.querySelectorAll('.bike-card').forEach(el=>{el.addEventListener('click',e=>{if(!e.target.closest('[data-compare]'))openDetail(el.dataset.id)});el.addEventListener('keydown',e=>{if(e.key==='Enter')openDetail(el.dataset.id)})});
 document.querySelectorAll('[data-compare]').forEach(btn=>btn.addEventListener('click',()=>toggleCompare(btn.dataset.compare)));
}
function openDetail(id,direction=0){const b=bikes.find(x=>x.id===id);currentDetailIndex=bikes.findIndex(x=>x.id===id);const modal=document.querySelector('#detailModal'),content=document.querySelector('#modalContent');content.innerHTML=`<div class="modal-hero"><p class="eyebrow"><span></span>${labels[b.cat[0]]} · ${b.brand}</p><h2>${b.name}</h2><p>${b.desc}</p><img class="modal-photo" src="${bikeImages[b.id]}" alt="${b.brand} ${b.name}" onerror="this.style.display='none'"></div><div class="modal-main"><div class="spec-grid">${[['Top speed',b.speed],['Peak power',b.power],['Battery',b.battery],['Claimed range',b.range],['Weight',b.weight],['Seat height',b.seat],['Wheels',b.wheels],['Typical price',b.price]].map(s=>`<div class="spec-cell"><span>${s[0]}</span><b>${s[1]}</b></div>`).join('')}</div><section class="modal-section"><h3>Who it suits</h3><p>${b.best}</p></section><section class="modal-section"><h3>Street-legality note</h3><p class="legal-note">${b.legal}</p></section><section class="modal-section"><h3>Research sources</h3><div class="source-links">${b.source.map(s=>`<a href="${s[1]}" target="_blank" rel="noopener">${s[0]} ↗</a>`).join('')}</div></section><section class="modal-section"><p><b>*Range is manufacturer-claimed under specific test conditions.</b> Real range depends on speed, terrain, temperature, tire pressure and rider weight. Model-year and regional specifications can change.</p></section></div>`;const previous=bikes[(currentDetailIndex-1+bikes.length)%bikes.length],next=bikes[(currentDetailIndex+1)%bikes.length];modal.querySelector('.profile-prev').setAttribute('aria-label',`Previous bike: ${previous.name}`);modal.querySelector('.profile-next').setAttribute('aria-label',`Next bike: ${next.name}`);if(direction){content.classList.remove('profile-slide-left','profile-slide-right');void content.offsetWidth;content.classList.add(direction>0?'profile-slide-right':'profile-slide-left')}if(!modal.open)modal.showModal()}
function navigateDetail(direction){const nextIndex=(currentDetailIndex+direction+bikes.length)%bikes.length;openDetail(bikes[nextIndex].id,direction)}
function toggleCompare(id){if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<2)selected.push(id);else selected=[selected[1],id];document.querySelector('#compareCount').textContent=`${selected.length}/2`;document.querySelector('#compareButton').disabled=selected.length!==2;render()}
function showCompare(){const a=bikes.find(b=>b.id===selected[0]),b=bikes.find(b=>b.id===selected[1]);const rows=[['Brand','brand'],['Top speed','speed'],['Peak power','power'],['Battery','battery'],['Claimed range','range'],['Weight','weight'],['Seat height','seat'],['Wheels','wheels'],['Typical price','price']];document.querySelector('#compareContent').innerHTML=`<div class="compare-table"><p class="eyebrow"><span></span>SIDE BY SIDE</p><h2>Core specification match-up</h2><div class="compare-row head"><span></span><span>${a.name}</span><span>${b.name}</span></div>${rows.map(r=>`<div class="compare-row"><b>${r[0]}</b><span>${a[r[1]]}</span><span>${b[r[1]]}</span></div>`).join('')}<div class="modal-section"><p>Figures are published specifications, not independent performance tests. Confirm the exact model year before buying.</p></div></div>`;document.querySelector('#compareModal').showModal()}
function renderActionVideos(){document.querySelector('#actionGrid').innerHTML=actionVideos.map(v=>{const b=bikes.find(x=>x.id===v.id);return `<a class="action-card" href="https://www.youtube.com/watch?v=${v.video}" target="_blank" rel="noopener noreferrer" aria-label="Watch ${b.name} ridden by ${v.creator} on YouTube"><div class="action-thumb"><img src="https://i.ytimg.com/vi/${v.video}/hqdefault.jpg" alt="${b.name} riding video thumbnail" loading="lazy"><span class="play-mark">▶</span><span class="watch-tag">WATCH ON YOUTUBE ↗</span></div><div class="action-body"><span>${b.brand} · ${b.name}</span><h3>${v.title}</h3><p>By <b>${v.creator}</b></p></div></a>`}).join('')}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');filter=btn.dataset.filter;render()}));
document.querySelectorAll('.filter').forEach(btn=>{if(btn.dataset.filter!=='all')btn.querySelector('b').textContent=bikes.filter(b=>b.cat.includes(btn.dataset.filter)).length});
[['powerFilter','power'],['speedFilter','speed'],['rangeFilter','range'],['sizeFilter','size']].forEach(([id,key])=>document.querySelector(`#${id}`).addEventListener('change',e=>{specFilters[key]=e.target.value;render()}));document.querySelector('#resetSpecFilters').addEventListener('click',()=>{Object.keys(specFilters).forEach(key=>specFilters[key]='all');document.querySelectorAll('.spec-filter select').forEach(select=>select.value='all');render()});
search.addEventListener('input',render);document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();render();document.querySelector('#library').scrollIntoView({behavior:'smooth',block:'start'})});document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==search){e.preventDefault();search.focus()}if(e.key==='Escape')document.querySelectorAll('dialog[open]').forEach(d=>d.close())});
document.querySelector('#compareButton').addEventListener('click',showCompare);document.querySelectorAll('.close-modal').forEach(btn=>btn.addEventListener('click',()=>btn.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
document.querySelectorAll('[data-profile-nav]').forEach(btn=>btn.addEventListener('click',()=>navigateDetail(Number(btn.dataset.profileNav))));document.addEventListener('keydown',e=>{if(!document.querySelector('#detailModal').open)return;if(e.key==='ArrowLeft')navigateDetail(-1);if(e.key==='ArrowRight')navigateDetail(1)});
render();renderActionVideos();
